package com.linkpets.core.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.linkpets.core.model.ZcAppraisalFavorite;

public interface ZcAppraisalFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_appraisal_favorite
     *
     * @mbg.generated Sat Aug 17 14:42:08 GMT+08:00 2019
     */
    @Delete({
        "delete from zc_appraisal_favorite",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_appraisal_favorite
     *
     * @mbg.generated Sat Aug 17 14:42:08 GMT+08:00 2019
     */
    @Insert({
        "insert into zc_appraisal_favorite (pk_id, appraisal_id, ",
        "user_id, create_time, ",
        "is_vaild)",
        "values (#{pkId,jdbcType=INTEGER}, #{appraisalId,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isVaild,jdbcType=INTEGER})"
    })
    int insert(ZcAppraisalFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_appraisal_favorite
     *
     * @mbg.generated Sat Aug 17 14:42:08 GMT+08:00 2019
     */
    int insertSelective(ZcAppraisalFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_appraisal_favorite
     *
     * @mbg.generated Sat Aug 17 14:42:08 GMT+08:00 2019
     */
    @Select({
        "select",
        "pk_id, appraisal_id, user_id, create_time, is_vaild",
        "from zc_appraisal_favorite",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    @ResultMap("com.linkpets.core.dao.ZcAppraisalFavoriteMapper.BaseResultMap")
    ZcAppraisalFavorite selectByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_appraisal_favorite
     *
     * @mbg.generated Sat Aug 17 14:42:08 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ZcAppraisalFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_appraisal_favorite
     *
     * @mbg.generated Sat Aug 17 14:42:08 GMT+08:00 2019
     */
    @Update({
        "update zc_appraisal_favorite",
        "set appraisal_id = #{appraisalId,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "is_vaild = #{isVaild,jdbcType=INTEGER}",
        "where pk_id = #{pkId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ZcAppraisalFavorite record);

    @Select({
		"<script> ",
        "select",
        "count(DISTINCT appraisal_id)",
        "from zc_appraisal_favorite",
        "where is_vaild = 1 and user_id = #{userId,jdbcType=VARCHAR}",
        "<if test='appraisalId != null'> AND appraisal_id = #{appraisalId}</if>",
		"</script> "
    })
	int getFavoriteCountByUser(@Param("appraisalId") String appraisalId, @Param("userId") String userId);
}