package com.linkpets.core.dao;

import com.linkpets.core.model.ZcBrandCollect;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ZcBrandCollectMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_brand_collect
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	@Delete({ "delete from zc_brand_collect", "where pk_id = #{pkId,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_brand_collect
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	@Insert({ "insert into zc_brand_collect (pk_id, brand_id, ", "user_id, create_time, ", "is_vaild)",
			"values (#{pkId,jdbcType=INTEGER}, #{brandId,jdbcType=VARCHAR}, ",
			"#{userId,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ", "#{isVaild,jdbcType=INTEGER})" })
	int insert(ZcBrandCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_brand_collect
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	int insertSelective(ZcBrandCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_brand_collect
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	@Select({ "select", "pk_id, brand_id, user_id, create_time, is_vaild", "from zc_brand_collect",
			"where pk_id = #{pkId,jdbcType=INTEGER}" })
	@ResultMap("com.linkpets.core.dao.ZcBrandCollectMapper.BaseResultMap")
	ZcBrandCollect selectByPrimaryKey(Integer pkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_brand_collect
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	int updateByPrimaryKeySelective(ZcBrandCollect record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_brand_collect
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	@Update({ "update zc_brand_collect", "set brand_id = #{brandId,jdbcType=VARCHAR},",
			"user_id = #{userId,jdbcType=VARCHAR},", "create_time = #{createTime,jdbcType=TIMESTAMP},",
			"is_vaild = #{isVaild,jdbcType=INTEGER}", "where pk_id = #{pkId,jdbcType=INTEGER}" })
	int updateByPrimaryKey(ZcBrandCollect record);

	@Select({
		"<script> ",
        "select",
        "count(DISTINCT brand_id)",
        "from zc_brand_collect",
        "where is_vaild = 1 and user_id = #{userId,jdbcType=VARCHAR}",
        "<if test='brandId != null'> AND brand_id = #{brandId}</if>",
        "</script>"
    })
	int getCollectCountByUser(@Param("brandId") String brandId, @Param("userId") String userId);

	@Update({ "update zc_brand_collect",
		"set is_vaild = 0",
		"where brand_id = #{brandId,jdbcType=VARCHAR} AND user_id = #{userId,jdbcType=VARCHAR}" })
	int delCollect(String brandId, String userId);
}