package com.linkpets.core.dao;

import com.linkpets.core.model.ZcCommodity;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ZcCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_commodity
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    @Delete({
        "delete from zc_commodity",
        "where commodity_id = #{commodityId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String commodityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_commodity
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    @Insert({
        "insert into zc_commodity (commodity_id, commodity_name, ",
        "brand_id, specification, ",
        "price, is_valid)",
        "values (#{commodityId,jdbcType=VARCHAR}, #{commodityName,jdbcType=VARCHAR}, ",
        "#{brandId,jdbcType=VARCHAR}, #{specification,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{isValid,jdbcType=INTEGER})"
    })
    int insert(ZcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_commodity
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    int insertSelective(ZcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_commodity
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    @Select({
        "select",
        "commodity_id, commodity_name, brand_id, specification, price, is_valid",
        "from zc_commodity",
        "where commodity_id = #{commodityId,jdbcType=VARCHAR}"
    })
    @ResultMap("com.linkpets.core.dao.ZcCommodityMapper.BaseResultMap")
    ZcCommodity selectByPrimaryKey(String commodityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_commodity
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(ZcCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_commodity
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    @Update({
        "update zc_commodity",
        "set commodity_name = #{commodityName,jdbcType=VARCHAR},",
          "brand_id = #{brandId,jdbcType=VARCHAR},",
          "specification = #{specification,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "is_valid = #{isValid,jdbcType=INTEGER}",
        "where commodity_id = #{commodityId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ZcCommodity record);

	List<Map<String, Object>> getList(Map<String, Object> param);
}