package com.linkpets.core.model;

import java.util.Date;

public class ZcAppraisal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_appraisal.appraisal_id
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    private String appraisalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_appraisal.title
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_appraisal.create_by
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_appraisal.create_time
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_appraisal.is_valid
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_appraisal.content
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_appraisal.appraisal_id
     *
     * @return the value of zc_appraisal.appraisal_id
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public String getAppraisalId() {
        return appraisalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_appraisal.appraisal_id
     *
     * @param appraisalId the value for zc_appraisal.appraisal_id
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public void setAppraisalId(String appraisalId) {
        this.appraisalId = appraisalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_appraisal.title
     *
     * @return the value of zc_appraisal.title
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_appraisal.title
     *
     * @param title the value for zc_appraisal.title
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_appraisal.create_by
     *
     * @return the value of zc_appraisal.create_by
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_appraisal.create_by
     *
     * @param createBy the value for zc_appraisal.create_by
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_appraisal.create_time
     *
     * @return the value of zc_appraisal.create_time
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_appraisal.create_time
     *
     * @param createTime the value for zc_appraisal.create_time
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_appraisal.is_valid
     *
     * @return the value of zc_appraisal.is_valid
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_appraisal.is_valid
     *
     * @param isValid the value for zc_appraisal.is_valid
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_appraisal.content
     *
     * @return the value of zc_appraisal.content
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_appraisal.content
     *
     * @param content the value for zc_appraisal.content
     *
     * @mbg.generated Sun Aug 11 14:03:03 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}