package com.linkpets.core.model;

import java.util.Date;

public class ZcBrandCollect {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand_collect.pk_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	private Integer pkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand_collect.brand_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	private String brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand_collect.user_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand_collect.create_time
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand_collect.is_vaild
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	private Integer isVaild;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand_collect.pk_id
	 * @return  the value of zc_brand_collect.pk_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public Integer getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand_collect.pk_id
	 * @param pkId  the value for zc_brand_collect.pk_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public void setPkId(Integer pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand_collect.brand_id
	 * @return  the value of zc_brand_collect.brand_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public String getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand_collect.brand_id
	 * @param brandId  the value for zc_brand_collect.brand_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand_collect.user_id
	 * @return  the value of zc_brand_collect.user_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand_collect.user_id
	 * @param userId  the value for zc_brand_collect.user_id
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand_collect.create_time
	 * @return  the value of zc_brand_collect.create_time
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand_collect.create_time
	 * @param createTime  the value for zc_brand_collect.create_time
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand_collect.is_vaild
	 * @return  the value of zc_brand_collect.is_vaild
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public Integer getIsVaild() {
		return isVaild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand_collect.is_vaild
	 * @param isVaild  the value for zc_brand_collect.is_vaild
	 * @mbg.generated  Sat Aug 17 15:12:22 GMT+08:00 2019
	 */
	public void setIsVaild(Integer isVaild) {
		this.isVaild = isVaild;
	}
}