package com.linkpets.core.model;

public class ZcBrand {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand.brand_id
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	private String brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand.brand_name
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand.logo_url
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	private String logoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand.origin
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	private String origin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand.scope
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_brand.is_vaild
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	private Integer isVaild;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand.brand_id
	 * @return  the value of zc_brand.brand_id
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public String getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand.brand_id
	 * @param brandId  the value for zc_brand.brand_id
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand.brand_name
	 * @return  the value of zc_brand.brand_name
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand.brand_name
	 * @param brandName  the value for zc_brand.brand_name
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand.logo_url
	 * @return  the value of zc_brand.logo_url
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public String getLogoUrl() {
		return logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand.logo_url
	 * @param logoUrl  the value for zc_brand.logo_url
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand.origin
	 * @return  the value of zc_brand.origin
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public String getOrigin() {
		return origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand.origin
	 * @param origin  the value for zc_brand.origin
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public void setOrigin(String origin) {
		this.origin = origin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand.scope
	 * @return  the value of zc_brand.scope
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand.scope
	 * @param scope  the value for zc_brand.scope
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_brand.is_vaild
	 * @return  the value of zc_brand.is_vaild
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public Integer getIsVaild() {
		return isVaild;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_brand.is_vaild
	 * @param isVaild  the value for zc_brand.is_vaild
	 * @mbg.generated  Sat Aug 17 15:12:42 GMT+08:00 2019
	 */
	public void setIsVaild(Integer isVaild) {
		this.isVaild = isVaild;
	}
}