package com.linkpets.core.model;

import java.math.BigDecimal;

public class ZcCommodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_commodity.commodity_id
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_commodity.commodity_name
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    private String commodityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_commodity.brand_id
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    private String brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_commodity.specification
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    private String specification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_commodity.price
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_commodity.is_valid
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_commodity.commodity_id
     *
     * @return the value of zc_commodity.commodity_id
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_commodity.commodity_id
     *
     * @param commodityId the value for zc_commodity.commodity_id
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_commodity.commodity_name
     *
     * @return the value of zc_commodity.commodity_name
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_commodity.commodity_name
     *
     * @param commodityName the value for zc_commodity.commodity_name
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_commodity.brand_id
     *
     * @return the value of zc_commodity.brand_id
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_commodity.brand_id
     *
     * @param brandId the value for zc_commodity.brand_id
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_commodity.specification
     *
     * @return the value of zc_commodity.specification
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_commodity.specification
     *
     * @param specification the value for zc_commodity.specification
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public void setSpecification(String specification) {
        this.specification = specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_commodity.price
     *
     * @return the value of zc_commodity.price
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_commodity.price
     *
     * @param price the value for zc_commodity.price
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_commodity.is_valid
     *
     * @return the value of zc_commodity.is_valid
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_commodity.is_valid
     *
     * @param isValid the value for zc_commodity.is_valid
     *
     * @mbg.generated Sun Aug 11 16:07:21 GMT+08:00 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}